/* smtp-config.h.  Generated by cmake from smtp-config.h.cmake  */

/* Define if you have cyrus-sasl2 libraries */
#cmakedefine HAVE_LIBSASL2 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#cmakedefine HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine HAVE_SYS_TYPES_H 1
