/* config.h.  Generated by cmake from config.h.cmake */


#define PACKAGE "kdepimlibs"

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H 1

/* Version number of package */
#define VERSION "3.9.02"
