/* config.h.  Generated by cmake from config.h.cmake */


#define PACKAGE "kdepimlibs"

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine HAVE_UNISTD_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H 1

/* Version number of package */
#define VERSION "3.9.02"

/* The size of a `unsigned long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG ${SIZEOF_UNSIGNED_LONG}

/* The size of a `uint64_t', as computed by sizeof. */
#define SIZEOF_UINT64_T ${SIZEOF_UINT64_T}

/* The size of a `unsigned long long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG_LONG ${SIZEOF_UNSIGNED_LONG_LONG}

#cmakedefine    HAVE_SNPRINTF 1
#cmakedefine    HAVE_ISWSPACE 1
#cmakedefine    HAVE_S_ISDIR 1
#cmakedefine    HAVE_S_ISREG 1
