/* config.h.  Generated by cmake from config.h.cmake */

/* Define to 1 if you have the <stdint.h> header file. */
#cmakedefine HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#cmakedefine HAVE_STDLIB_H 1

/* Define to 1 if you have the <wctype.h> header file. */
#cmakedefine HAVE_WCTYPE_H 1

/* Define to 1 if you have the `snprintf' function. */
#cmakedefine    HAVE_SNPRINTF 1

/* Define to 1 if you have the `iswspace' function. */
#cmakedefine    HAVE_ISWSPACE 1

